home:
    path: /
    defaults: { _controller: BinaerpilotenLigaBundle:Default:index }
    
armee:
    resource: "@BinaerpilotenLigaBundle/Controller/ArmeeController.php"
    type: annotation
    
spiel:
    resource: "@BinaerpilotenLigaBundle/Controller/SpielController.php"
    type: annotation
    
user:
    resource: "@BinaerpilotenLigaBundle/Controller/UserController.php"
    type: annotation