home:
    path: /
    defaults: { _controller: BinaerpilotenLigaBundle:Default:index }
    
armee:
    resource: "@BinaerpilotenLigaBundle/Controller/ArmeeController.php"
    type: annotation
    
spiel:
    resource: "@BinaerpilotenLigaBundle/Controller/SpielController.php"
    type: annotation
    
user:
    resource: "@BinaerpilotenLigaBundle/Controller/UserController.php"
    type: annotation
    
volk:
    resource: "@BinaerpilotenLigaBundle/Controller/VolkController.php"
    type: annotation
    
spielfilter:
    resource: "@BinaerpilotenLigaBundle/Controller/SpielFilterController.php"
    type: annotation    
    
mission:
    resource: "@BinaerpilotenLigaBundle/Controller/MissionController.php"
    type: annotation    