binaerpiloten_liga_homepage:
    path: /
    defaults: { _controller: BinaerpilotenLigaBundle:Default:index }
    
user_profile:
    path: /profile
    defaults: { _controller: BinaerpilotenLigaBundle:User:profile }