parameters:
#    binaerpiloten_liga.example.class: Binaerpiloten\LigaBundle\Example

#    binaerpiloten_liga.example:
#        class: %binaerpiloten_liga.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    liga_user.registration.form.type:
        class: Binaerpiloten\LigaBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: liga_user_registration }
    liga_user.profile.form.type:
        class: Binaerpiloten\LigaBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: liga_user_profile }
    binaerpiloten.twig.armee_extension:
        class: Binaerpiloten\LigaBundle\Twig\ArmeeExtension
        arguments: [ @doctrine.orm.entity_manager, @security.context ]
        tags:
            - { name: twig.extension }
    binaerpiloten.twig.token_extension:
        class: Binaerpiloten\LigaBundle\Twig\TokenExtension
        arguments: [ @service_container ]
        tags:
            - { name: twig.extension }