parameters:
#    binaerpiloten_liga.example.class: Binaerpiloten\LigaBundle\Example

services:
#    binaerpiloten_liga.example:
#        class: %binaerpiloten_liga.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
